import { afterEach, it, expect } from 'vitest';
import { makeWormSim, resetWormSim } from '../worm/healerWorm/wormSim.js';
import { stageStory, replenishStoryTunnel } from '../worm/story/runtime.js';
import { storyLevel } from '../worm/story/levels.js';
import { getActiveTunnels, findStickerByStableKey } from '../worm/wormLogic.js';
import { flipStickerPair, buildManifoldGridMap } from '../game/manifoldLogic.js';
import { rotateSliceCubies } from '../game/cubeRotation.js';
import { resetLiveRotation } from '../worm/liveRotation.js';
afterEach(resetLiveRotation);
it('opens a queued mouth at its rotated location after a previous pair clears', () => {
  resetLiveRotation();
  const sim = makeWormSim(5); resetWormSim(sim,5,{orbCount:0,wormholeInterval:9999});
  const practice = stageStory(sim,5,storyLevel(6));
  let cubies = practice.cubies;
  const mouth = getActiveTunnels(cubies,5)[0].entry;
  cubies = flipStickerPair(cubies,5,mouth.x,mouth.y,mouth.z,mouth.dirKey,buildManifoldGridMap(cubies,5));
  const queued = practice.pendingMouths[0];
  cubies = rotateSliceCubies(cubies,5,'row',4,1);
  sim.powerups=[]; sim.specials=[];
  const state = {cubies,animState:null};
  sim.tunnelPassages.push({});
  expect(replenishStoryTunnel(sim,practice,state,5)).toBeNull();
  expect(practice.pendingMouths).toHaveLength(4);
  sim.tunnelPassages=[];
  const next = replenishStoryTunnel(sim,practice,state,5);
  expect(next).not.toBeNull();
  expect(getActiveTunnels(next,5)).toHaveLength(2);
  expect(practice.pendingMouths).toHaveLength(3);
  const pos = findStickerByStableKey(next,5,queued);
  const sticker = next[pos.x][pos.y][pos.z].stickers[pos.dirKey];
  expect(sticker.curr).not.toBe(sticker.orig);
  expect(replenishStoryTunnel(sim,practice,{...state,cubies:next},5)).toBeNull();
});
